const { Groq } = require('groq-sdk');

const groq = new Groq({
  apiKey: process.env.GROQ_API_KEY
});

async function generateContent(prompt, context = null) {
  try {
    console.log("🚀 Groq AI analyzing code...");
    
    let systemPrompt = `You are an expert code reviewer. Review the given code and provide feedback in this EXACT format:

# 🎯 Code Review Summary

## 📊 Overall Score: X/10

## ✅ Strengths
- Bullet point 1
- Bullet point 2

## ⚠️ Issues Found
1. **Issue Title** - Brief description
2. **Issue Title** - Brief description

## 🔧 Critical Improvements
### 1. Issue Name
**Problem:** Clear description
**Fix:** 
\`\`\`language
// Improved code here
\`\`\`

### 2. Issue Name  
**Problem:** Clear description
**Fix:**
\`\`\`language
// Improved code here
\`\`\`

## ✨ Optimized Version
\`\`\`language
// Complete improved code
\`\`\`

## 💡 Key Recommendations
- Recommendation 1
- Recommendation 2

## 📈 Next Steps
1. Step 1
2. Step 2

---
*Review generated by AI Code Reviewer*

**RULES:**
- Keep it concise (max 300 words for simple code)
- Use simple language
- Focus on 3-4 most important issues
- Show improved code examples
- No unnecessary tables
- No academic jargon
- Be practical and actionable`;

    // Enhanced prompt for project files
    if (context) {
      systemPrompt = `You are analyzing a file from a larger project. Context: ${context}

${systemPrompt}

**ADDITIONAL CONSIDERATIONS for project files:**
- Consider how this file fits into the larger project
- Check for imports/dependencies
- Look for consistency with project structure
- Suggest architecture improvements if needed`;
    }

    const chatCompletion = await groq.chat.completions.create({
      messages: [
        {
          role: "system",
          content: systemPrompt
        },
        {
          role: "user",
          content: `Review this code:\n\n${prompt}`
        }
      ],
      model: "openai/gpt-oss-120b",
      temperature: 0.5,
      max_tokens: 1500,
      top_p: 0.9,
    });

    const review = chatCompletion.choices[0]?.message?.content;
    console.log("✅ Review generated!");
    
    return review || getFallbackReview(prompt);
    
  } catch (error) {
    console.error("❌ Error:", error.message);
    return getFallbackReview(prompt);
  }
}

// Simple fallback
function getFallbackReview(code) {
  return `# 🎯 Quick Code Review

## 📊 Overall: Basic but needs improvement

## ✅ Strengths
- Simple and readable
- Clear structure

## ⚠️ Issues
1. **Hardcoded values** - Function not reusable
2. **Missing documentation** - No comments or docs

## 🔧 Fix Needed
**Problem:** Function always returns same value
**Fix:**
\`\`\`javascript
function sum(a, b) {
  return a + b;
}
\`\`\`

## 💡 Recommendation
Add parameters to make function reusable.`;
}

// Export both single and project analysis
module.exports = generateContent;
module.exports.analyzeWithContext = async (code, context) => {
  return generateContent(code, context);
};